CC := cc
CFLAGS := -std=c11 -g -Wall -g3 -Ofast -Wextra -pedantic -march=native

fuente1: src/fuente1.c	
	@$(CC) $(CFLAGS) src/fuente1.c -o bin/fuente1

fuente2: src/fuente2.c	
	@$(CC) $(CFLAGS) src/fuente2.c -o bin/fuente2

fuente3: src/fuente3.c	
	@$(CC) $(CFLAGS) src/fuente3.c -o bin/fuente3